# Generated by Django 5.0.4 on 2024-04-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piano_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
