# Generated by Django 5.0.4 on 2024-04-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piano_project', '0004_teacher_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
